name: batt_onboarding
description: A starting point for Dart libraries or applications.
version: 1.0.5
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  chopper: ^8.0.3
  dio: ^5.7.0
  flutter_form_builder: ^9.7.0
  font_awesome_flutter: ^10.8.0
  form_builder_validators: ^11.1.1
  google_mlkit_text_recognition: ^0.14.0 
  http: ^1.3.0
  http_parser: ^4.1.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: any
  pinput: ^5.0.1
  sealed_countries: any
  universal_io: ^2.2.2

  flutter_localizations:
    sdk: flutter 
  
  batt_ds:
    #path: ../batt_ds
    git:
      url: https://github.com/Battmobility/be.battmobility.batt_ds
      ref: 'main'

dev_dependencies:
  build_runner: ^2.4.9
  chopper_generator: ^8.0.3
  json_serializable: ^6.8.0
  swagger_dart_code_generator: ^2.10.4
  flutter_gen: ^5.8.0
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true