name: batt_onboarding
description: A starting point for Dart libraries or applications.
version: 1.0.5
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  chopper: ^8.0.3
  intl: any
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  
  flutter_localizations:
    sdk: flutter 
  
  batt_ds:
    git:
      url: https://github.com/Battmobility/be.battmobility.batt_ds
      ref: 'main'

dev_dependencies:
  build_runner: ^2.4.9
  chopper_generator: ^8.0.3
  json_serializable: ^6.8.0
  swagger_dart_code_generator: ^2.10.4
  flutter_gen: ^5.8.0
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true