name: batt_onboarding
description: A starting point for Dart libraries or applications.
version: 1.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  
  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true