name: batt_onboarding
description: Onboarding for BattMobility/MobilityOS
version: 1.1.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  chopper: ^8.0.3
  dio: ^5.7.0
  flutter_form_builder: ^9.7.0
  font_awesome_flutter: ^10.8.0
  form_builder_validators: ^11.1.1
  google_mlkit_text_recognition: ^0.14.0 
  http: any
  http_parser: ^4.1.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  pinput: ^5.0.1
  sealed_countries: ^2.1.0

  flutter_localizations:
    sdk: flutter 
  
  batt_ds:
    #path: ../batt_ds
    git:
      url: https://github.com/Battmobility/be.battmobility.batt_ds.git
      ref: 'main'
  
  batt_kit:
    git:
      url: https://github.com/Battmobility/batt_api.git
      ref: 'main'


dev_dependencies:
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  json_serializable: ^6.9.4
  swagger_dart_code_generator: ^3.0.1
  flutter_gen: ^5.10.0
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true